# Generated by Django 4.0.3 on 2022-06-23 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0002_alter_ads_date_to'),
    ]

    operations = [
        migrations.AddField(
            model_name='news_table',
            name='pub_draft',
            field=models.BooleanField(default=True),
            preserve_default=False,
        ),
    ]
