# Generated by Django 4.0.3 on 2022-06-27 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0003_news_table_pub_draft'),
    ]

    operations = [
        migrations.CreateModel(
            name='addcategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cat_dec', models.TextField()),
            ],
        ),
    ]
