# Generated by Django 4.0.3 on 2022-06-27 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('info', '0004_addcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='addcategory',
            name='category_name',
            field=models.TextField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
